version: "3"

volumes:
    mysql_data:

networks:
    backend:
        ipam:
            config:
                - subnet: 172.30.1.0/24
    frontend:
        ipam:
            config:
                -   subnet: 172.30.0.0/24

services:
    app:
        image: jlisher/php56-phalcon-2-dev:latest
        build:
            context: .
            args:
                RUN_UID: ${RUN_UID:-33}
                RUN_GID: ${RUN_GID:-33}
        restart: unless-stopped
        volumes:
            - ./app:/app
        networks:
            backend:
                ipv4_address: 172.30.1.3

    web:
        image: docker.io/library/httpd:2.4-alpine
        restart: unless-stopped
        volumes:
            - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
#            - ./httpd/server.crt:/usr/local/apache2/conf/server.crt
#            - ./httpd/server.key:/usr/local/apache2/conf/server.key
            - ./app:/usr/local/apache2/htdocs
        networks:
            backend:
                ipv4_address: 172.30.1.2
            frontend:
                ipv4_address: 172.30.0.2

    mysql:
        image: docker.io/library/mysql:5
        restart: unless-stopped
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-data}
            MYSQL_USER: ${MYSQL_USER:-user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pass}
            MYSQL_RANDOM_ROOT_PASSWORD: 1
        networks:
            backend:
                ipv4_address: 172.30.1.4
